# Generated by Django 2.0.1 on 2018-01-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitter', models.CharField(max_length=30)),
                ('solver', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('A', 'Assigned'), ('C', 'Closed')], max_length=1)),
                ('category', models.CharField(choices=[('B', 'Bug'), ('E', 'Enhancements'), ('D', 'Documentation')], max_length=1)),
                ('opened', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
